"""Create users table

Revision ID: 001
Revises:
Create Date: 2024-12-22 17:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False, comment="Internal user ID"),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False, comment="Telegram user ID"),
        sa.Column(
            "username",
            sa.String(length=255),
            nullable=True,
            comment="Telegram username (@username)",
        ),
        sa.Column(
            "first_name", sa.String(length=255), nullable=True, comment="Telegram first name"
        ),
        sa.Column("last_name", sa.String(length=255), nullable=True, comment="Telegram last name"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Whether user is active"),
        sa.Column(
            "language_code", sa.String(length=10), nullable=True, comment="User's language code"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last update timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=False)
    op.create_unique_constraint("uq_users_telegram_id", "users", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_telegram_id", "users", type_="unique")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
